export default {
  products: [
    {
      _id: "1",
      name: "Rog Q25F9B2 Monitor",
      category: "Monitors",
      image: "/images/download.png",
      price: 200000,
      brand: "Asus",
      rating: 4.9,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Pavilion Sentry Monitor",
      category: "Monitors",
      image: "/images/samsung-02.png",
      price: 150000,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 43,
      countInStock: 8,
    },
    {
      _id: "3",
      name: "Pavilion Sentry Monitor",
      category: "Monitors",
      image: "/images/samsung-monitor.png",
      price: 150000,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 43,
      countInStock: 8,
    },
    {
      _id: "4",
      name: "Rog Q25F9B2 Monitor",
      category: "Monitors",
      image: "/images/download.png",
      price: 200000,
      brand: "Asus",
      rating: 4.9,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Rog Q25F9B2 Monitor",
      category: "Monitors",
      image: "/images/samsung-02.png",
      price: 200000,
      brand: "Asus",
      rating: 4.9,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Rog Q25F9B2 Monitor",
      category: "Monitors",
      image: "/images/download.png",
      price: 200000,
      brand: "Asus",
      rating: 4.9,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
